### ISSUE TITLE
Toolkit 1.4.0 Doesnot work in Node

### ISSUE THREAD

**Issue by arunoda** [ollym/toolkit#25]
Here's the Node REPL Output

```
> require('toolkit')
{ version: '1.4.0' }
> Array.intersect([[2,3,4], [3,4,5]])
TypeError: Object function Array() { [native code] } has no method 'intersect'
    at [object Context]:1:7
    at Interface.<anonymous> (repl.js:171:22)
    at Interface.emit (events.js:64:17)
    at Interface._onLine (readline.js:153:10)
    at Interface._line (readline.js:408:8)
    at Interface._ttyWrite (readline.js:585:14)
    at ReadStream.<anonymous> (readline.js:73:12)
    at ReadStream.emit (events.js:81:20)
    at ReadStream._emitKey (tty_posix.js:307:10)
    at ReadStream.onData (tty_posix.js:70:12)
> 
```

**Comment by ollym** [comment]
It doesn't work on REPL. Will investigate why.

**Comment by arunoda** [comment]
Thats great. And works greatly with .js files.
Good job.

On Sat, Sep 24, 2011 at 3:58 AM, Oliver Morgan <
reply@reply.github.com>wrote:

> It doesn't work on REPL. Will investigate why.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ollym/toolkit/issues/25#issuecomment-2183503

## 

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by ollym** [comment]
The problem with REPL is that it's using vm.runScriptInNewContext() which re-creates all the old builtin objects like Array etc. which is what toolkit extends. I've been playing around with a few things to get this working without having to submit a patch like:

require('toolkit').repl()

But I'm having no luck. Will keep you posted.

**Comment by arunoda** [comment]
The point about REPL is once someone saw the documentation first thing is
play with the REPL.
As I do. So We get confused because it doesn't work with the REPL.
And other than that no big issues.

Since This is not fixed.
It's better you can add some not on the documentation saying do not test on
the REPL :)

Cheers.

On Sat, Sep 24, 2011 at 7:46 PM, Oliver Morgan <
reply@reply.github.com>wrote:

> The problem with REPL is that it's using vm.runScriptInNewContext() which
> re-creates all the old builtin objects like Array etc. which is what toolkit
> extends. I've been playing around with a few things to get this working
> without having to submit a patch like:
> 
> require('toolkit').repl()
> 
> But I'm having no luck. Will keep you posted.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ollym/toolkit/issues/25#issuecomment-2186491

## 

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda
