### ISSUE TITLE
Documentation (and function header) wrong in String.chars

### ISSUE THREAD

**Issue by archaeron** [ollym/toolkit#27]
https://github.com/ollym/toolkit/blob/master/lib/string.js#L66

**Comment by ollym** [comment]
Thanks. There are loads of issues like that. I plan to complete the documentation website - making sure it's working in all major browsers then I'm going to spend hours purging through every doc making sure it's correct and flushing out the examples/parameter descriptions.

**Comment by archaeron** [comment]
you're welcome :) i wish that you succeed :)

**Comment by ollym** [comment]
So are you bro! Depends on what you mean by succeed. As far as I'm concerned I've created an awesome toolkit which will help me in all my projects. That was what I wanted to create, thats what I feel I've managed. So as far as I'm concerned, i've succeeded already!! Would be nice to see people using it too tho :)

PS. What do you think of the new docs?

**Comment by archaeron** [comment]
i've looked at the code. it looks awesome :) It is interesting to look how others program :)
I'll try and use it in a project.

The new docs are great. they look really good and work now :d i've tried the one before in safari, chrome and FF and it didn't work in any of them. There are still some bugs in the new one though :)
